version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - dupl
    - dupword
    - errname
    - errorlint
    - forbidigo
    - forcetypeassert
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gosec
    - gosmopolitan
    - importas
    - inamedparam
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - perfsprint
    - predeclared
    - reassign
    - revive
    - sqlclosecheck
    - tagliatelle
    - testifylint
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
  disable:
    - staticcheck
  settings:
    decorder:
      dec-order:
        - type
        - const
        - var
        - func
    dupl:
      threshold: 100
    errorlint:
      errorf: true
      errorf-multi: true
      asserts: true
      comparison: true
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
      ignore-enum-members: Example.+
      ignore-enum-types: Example.+
      package-scope-only: false
      explicit-exhaustive-map: false
      explicit-exhaustive-switch: false
      default-case-required: false
    forbidigo:
      forbid:
        - pattern: ^print.*$
        - pattern: ^fmt\.Print.*$
          msg: Do not commit print statements.
        - pattern: fmt\.Print.*(# Do not commit print statements\.)?
        - pattern: ^spew\.(ConfigState\.)?Dump$
        - pattern: ^v1.Dump$
          pkg: ^example.com/pkg/api/v1$
    gocognit:
      min-complexity: 30
    govet:
      disable:
        - fieldalignment
      enable-all: true
    perfsprint:
      int-conversion: true
      err-error: true
      errorf: true
      sprintf1: true
    predeclared:
      qualified-name: true
    revive:
      rules:
        - name: unexported-return
          disabled: true
    unused:
      field-writes-are-uses: true
      post-statements-are-reads: false
      exported-fields-are-used: true
      parameters-are-used: true
      local-variables-are-used: true
      generated-is-used: true
    whitespace:
      multi-if: false
      multi-func: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - _test.go$
      - third_party$
      - builtin$
      - examples$
issues:
  uniq-by-line: true
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - _test.go$
      - third_party$
      - builtin$
      - examples$
