openapi: 3.0.4
info:
  title: YeenCloud - Identity Service
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: user
    description: Operations about user
paths:
  /identity/users:
    post:
      tags:
        - user
      summary: Create a new user.
      operationId: createUser
      requestBody:
        description: Create a new user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreation'
        required: true
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: 'https://raw.githubusercontent.com/yeencloud/lib-httpserver/refs/heads/main/contract/httpserver.yaml#/components/schemas/Response'
                  - type: object
                    properties:
                      body:
                        $ref: '#/components/schemas/UserProfile'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/yeencloud/lib-httpserver/refs/heads/main/contract/httpserver.yaml#/components/schemas/ResponseError'
        '403':
          description: Already logged in
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/yeencloud/lib-httpserver/refs/heads/main/contract/httpserver.yaml#/components/schemas/ResponseError'
components:
  schemas:
    UserCreation:
      type: object
      properties:
        username:
          type: string
          example: johndoe
        password:
          type: string
          format: password
          example: securepassword123
        email:
          type: string
          format: email
          example: example@example.com
    UserProfile:
      type: object
      properties:
        id:
          type: string
          example: 12345